spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/home_exchange_simple?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    username: root
    password: workbench
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  sql:
#    init:
#      mode: always
  jpa:
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

server:
  error:
    include-exception: true
    whitelabel:
      enabled: on

  #Cloudinary Properties
cloudinary:
  api-key: "118818994231496"
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: "dttt8mefd"
