version: '3.4'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=home_exchange_simple
      - MYSQL_USER=he
      - MYSQL_PASSWORD=workbench

  HomeExchange_SimpleVersion:
    image: mimip/home_exchange:v1
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=he
      - MYSQL_PASSWORD=workbench
      - HOSTNAME=http://localhost:8080